export const OBTENER_CLIENTES = 'OBTENER_CLIENTES';
export const OBTENER_CLIENTE = 'OBTENER_CLIENTE';
export const NUEVO_CLIENTE = 'NUEVO_CLIENTE';
export const ACTUALIZAR_CLIENTE = 'ACTUALIZAR_CLIENTE';
export const ELIMINAR_CLIENTE = 'ELIMINAR_CLIENTE';

export const OBTENER_PRODUCTOS = 'OBTENER_PRODUCTOS';
export const OBTENER_PRODUCTO = 'OBTENER_PRODUCTO';
export const NUEVO_PRODUCTO = 'NUEVO_PRODUCTO';
export const ACTUALIZAR_PRODUCTO = 'ACTUALIZAR_PRODUCTO';
export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO';
