export const OBTENER_CLIENTES = 'OBTENER_CLIENTES';
export const OBTENER_CLIENTE = 'OBTENER_CLIENTE';
export const NUEVO_CLIENTE = 'NUEVO_CLIENTE';
export const ACTUALIZAR_CLIENTE = 'ACTUALIZAR_CLIENTE';
export const ELIMINAR_CLIENTE = 'ELIMINAR_CLIENTE';
